### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by anebi** [cetic/helm-pgadmin#5]
Hello,

I try to install pgadmin using your chart. I set service.type to be ClusterIP and port 80. I plan to use ingress controller in order to access pgadmin, but I get following error:

`[2019-07-11 13:38:28 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-07-11 13:38:28 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2019-07-11 13:38:28 +0000] [1] [INFO] Using worker: threads
[2019-07-11 13:38:28 +0000] [76] [INFO] Booting worker with pid: 76
[2019-07-11 13:38:33 +0000] [76] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
super(ThreadWorker, self).init_process()
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
self.load_wsgi()
File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
self.wsgi = self.app.wsgi()
File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
return self.load_wsgiapp()
File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
return util.import_app(self.app_uri)
File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
__import__(module)
File "/pgadmin4/run_pgadmin.py", line 4, in <module>
from pgAdmin4 import app
File "/pgadmin4/pgAdmin4.py", line 131, in <module>
server_port = int(port)
ValueError: invalid literal for int() with base 10: 'tcp://10.43.140.25:80'
[2019-07-11 13:38:33 +0000] [76] [INFO] Worker exiting (pid: 76)
[2019-07-11 13:38:33 +0000] [1] [INFO] Shutting down: Master
[2019-07-11 13:38:33 +0000] [1] [INFO] Reason: Worker failed to boot.`

How can I solve this?

Thank you in advance!

Best regards,
Ali Nebi

**Comment by anebi** [comment]
I read that some ENV variable must be set like:

fixed by adding
- name: PGADMIN_PORT
value: "5050"

**Comment by banzo** [comment]
Hi Ali, maintainers of this repo will be unavailable for the next 2 weeks, so feel free to submit a PR if/when you find a working solution.

**Comment by alexnuttinck** [comment]
Fixed in PgAdmin Helm Chart v0.1.5.
